services:
    tmf629v5:
        build: . -t
        image: ghcr.io/dmiano/ri_docker_images/ri629-ghcr:latest
        ports:
        - 8629:8629
        stdin_open: true
        tty: true
        depends_on:
        - mongo
        external_links:
        - mongo
        environment:
            DB_URL: mongodb://mongo:27071
    mongo:
        #container_name: database_container
        image: mongo:4.4.6
        ports:
        - 27017:27017
        restart: unless-stopped
        volumes:
        - ctk_data:/data/db
        #image: "629"        
version: '3.9'
volumes:
    ctk_data: {}
